# Generated by Django 3.0.3 on 2020-04-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semi_Restful_App', '0002_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
